server:
  port: 80

spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.canyan7n.springcloud.entities

eureka:
  client:
    register-with-eureka: true #注册进Eureka
    # 是否从server抓取注册信息 单节点无所谓，但集群必须设置true 配合ribbon分配负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka