server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #服务器实例名称
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false #自己是注册中心，我的职责是维护实例，不需要检索服务
    service-url:
      #设置 与eureka server交互的地址 查询服务和注册服务都要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root